### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by Bezdarnost** [opendatalab/UniMERNet#1]
Hello, thank you so much for your excellent research!

I have a few questions:

1. When will you be able to provide the training code? Could you possibly share it with me within the next few days? I would greatly appreciate it.
2. Why didn't you use InkML as the input format for the model?
3. Do you plan to incorporate this new dataset from Google in your training process? (https://arxiv.org/pdf/2404.10690v1)

**Comment by wangbinDL** [comment]
Hi, Thanks for your interest in our work!

**Training Code Availability**: We are currently finalizing the training code and expect to release it by the end of May. Stay tuned for the update.

**Choice of Input Format**: We opted for LaTeX over InkML because our research is focused on image-based formula recognition, which applies to a broader range of sources such as PDF documents, webpage screenshots, and photographed equations. LaTeX annotations provide a more universal approach for our purposes, allowing us to work with images directly without the need for the trajectory and velocity data that InkML caters to with online handwriting devices.

**Incorporating Google's Dataset**: We are indeed aware of Google's MathWriting dataset and recognize the value of high-quality data in enhancing formula recognition capabilities. We plan to benchmark our model using this dataset and integrate it into our training process. Should the results prove beneficial, we intend to share these improvements with the community.
