### ISSUE TITLE
Great work. When will the training code be open source?

### ISSUE THREAD

**Issue by pjpanadas** [opendatalab/UniMERNet#3]

**Comment by wangbinDL** [comment]
Hi, Thanks for your interest in our work!

We sincerely apologize for the delay in releasing the training code. Originally, we planned to open-source the training code by the end of May. However, due to some urgent work-related requirements that needed our immediate attention, this process has been delayed.

We are committed to providing high-quality and usable code to our community. To ensure this, we need a bit more time to prepare the training code properly. We are now targeting to release the training code by the end of July.

Thank you for your patience and understanding. Please stay tuned for further updates.
